### PR TITLE
fix: Use show-line-numbers instead of line-numbers

### PR DESCRIPTION
**Pull request by Jaezmien**
## 📑 Description
Fixes an issue where `line_numbers` would throw an error since the parameter is `--show-line-numbers`

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation

### CODE REVIEW

**Review by isabelroses — COMMENTED** [review]
Why not just change the allowed options from `line_numbers` to `show_line_numbers`.

**Comment by Jaezmien** [comment]
> Why not just change the allowed options from `line_numbers` to `show_line_numbers`.

Just recently realized this, but even with that - it doesn't work all the time.

See: 
image
image

`--show-line-numbers` doesn't take in a value, so freeze tries to use the appended `true` as an argument
image

This is why I forced `line_numbers` to return the parameter instead.

(Sorry, accidentally pressed close pull request!)

**Comment by isabelroses** [comment]
> `--show-line-numbers` doesn't take in a value, so freeze tries to use the appended `true` as an argument

if thats the case then that means this is an issue with how handling boolean flags should work because then the `window` option for example should fail.

**Comment by isabelroses** [comment]
Just fixed the boolean options with e76bf9f, hopefully you can try merge with main and test the suggested changes.

**Comment by Jaezmien** [comment]
It works! But now I'm a bit worried about options that are inside tables, since it doesn't seem like they're handled with this change (e.g. `font.ligatures`)

**Comment by isabelroses** [comment]
> It works! But now I'm a bit worried about options that are inside tables, since it doesn't seem like they're handled with this change (e.g. `font.ligatures`)

oh, thats a good catch.

**Comment by isabelroses** [comment]
> > It works! But now I'm a bit worried about options that are inside tables, since it doesn't seem like they're handled with this change (e.g. `font.ligatures`)
> 
> oh, thats a good catch.

that should be fixed by 471ab9e now.

**Comment by Jaezmien** [comment]
I've also tried rewriting `M.get_arguments` a little bit with f2af1885a58c227704ed3336d98bb609882651c8 - would this work better?

**Comment by Jaezmien** [comment]
Ah! I've forgotten that tables also prepend the current table key to the parameter. I think that yours actually work right now! (Though currently the config and test still refers to `line_numbers` instead of `show_line_numbers`)

**Comment by isabelroses** [comment]
> I've also tried rewriting `M.get_arguments` a little bit with [f2af188](https://github.com/isabelroses/charm-freeze.nvim/commit/f2af1885a58c227704ed3336d98bb609882651c8) - would this work better?

I believe that it currently fails to call the command since it can parse the `font` but then it trys to call `--family` when it should call `--font.family`

**Review by isabelroses — COMMENTED** [review]
Cool, the latest changes seem to work and pass all the tests, if you can correct the merge confits we should be good to merge.

**Review by isabelroses — APPROVED** [review]
LGTM, thanks for the contribution <3

**Pull request merged**
