### PR TITLE
fix: correctly handle table fields in options when parsing arguments

### PR DESCRIPTION
**Pull request by comfysage**
unexpected errors occured after fixing #2

### CODE REVIEW

**Comment by isabelroses** [comment]
> unexpected errors occured after fixing #2

hum, maybe i should add some tests lol. Thanks for the PR ill test it asap.

**Comment by comfysage** [comment]
yes, ... i forgot to test it after the last pr (#3)

... should now be fixed tho :)

**Comment by isabelroses** [comment]
I seem to be getting an error.

> attempt to call field 'tbl_isarray' (a nil value)

**Review by isabelroses — APPROVED** [review]
Thanks for being so quick on this. It looks like it works!

**Pull request merged**
